apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: custom-deploy-mlflow
spec:
  refreshInterval: 1h
  data:
  - secretKey: MYSQL_PWD
    remoteRef:
      key: MLFlowRDSDatabaseSecret
      property: password
      decodingStrategy: None
  - secretKey: MYSQL_USERNAME
    remoteRef:
      key: MLFlowRDSDatabaseSecret
      property: username
      decodingStrategy: None
  - secretKey: MYSQL_DATABASE
    remoteRef:
      key: MLFlowRDSDatabaseSecret
      property: dbname
      decodingStrategy: None
  - secretKey: MYSQL_HOST
    remoteRef:
      key: MLFlowRDSDatabaseSecret
      property: host
      decodingStrategy: None

  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-manager
  target:
    name: custom-deploy-mlflow
    creationPolicy: Owner
    deletionPolicy: Retain
